[toolchain]
anchor_version = "0.30.1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
zk_credit_verifier = "9fx3329hTirtrGA77bQ3qTQMHgkcYbiMJTSbY1kSK1Kh"
zk_lending_pool = "HbHw6ib3eCfxbV1tv7X817VZ9J9tR4ZLGpNEQJ2jYDQo"
zkc_token = "4A1AR7H5VHQzwM7QuucYDHKTrQWt9HQ1GyEB4gh4pump"
zk_governance = "4FE94XY5Az6fS2PCBxd2PZtzPq5EiXYT5EFPzYj53QkT"

[scripts]
test = "cargo test"
build = "cargo build-bpf"
deploy = "cargo build-bpf && solana program deploy"
